/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package fr.gsb.rv.dr;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

import fr.gsb.rv.dr.vues.PanneauPraticiens;

class PanneauPraticiensTest {
    @Test
    void panneauPraticiensHasCritereTri() {
        PanneauPraticiens classUnderTest = new PanneauPraticiens();
        assertNotNull(classUnderTest.getCritereTri(), "un critere de tri doit être sélectionné");
    }
}
